#version: "3.8"

services:

  server:
    build: ./server
    ports:
      - "9000:8080"
    environment:
      - MONGO_URI=mongodb+srv://gibbradmin:skeletonkey@gibbrcluster.uchffb9.mongodb.net/gibbr?retryWrites=true&w=majority
      - JWT_SECRET=EmilMatildaAlexPontusGibbr
      - RAWG_API_KEY=77d89f43b46a4dfe95c8153ef56e94dc
      - PORT=8080     # app listens on 8080 inside container

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server